version: '3.9'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    container_name: mysql

  app:
    image: webdevops/php:7.3
    hostname: php-fpm
    volumes:
      - "./:/app"
    working_dir: "/app"
#    command: bash -c "curl -sL https://deb.nodesource.com/setup_12.x | bash - && apt-get install -y nodejs"
    depends_on:
      - mysql
    container_name: app

  nginx:
    image: webdevops/nginx
    hostname: nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php-fpm:9000
    ports:
      - "80:80"
    volumes:
      - "./:/app"
    depends_on:
      - app
    container_name: nginx
